# Generated by Django 3.1.7 on 2021-03-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('CP', 'C++'), ('PY', 'Python'), ('JA', 'Java')], default='JA', max_length=2),
        ),
    ]
