# Generated by Django 3.1.7 on 2021-04-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210331_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('instructor', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='group',
        ),
        migrations.AddField(
            model_name='problem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='judge.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='judge.Course'),
        ),
    ]
