# Generated by Django 3.1.7 on 2021-04-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20210405_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='course',
            new_name='courses',
        ),
    ]
