# Generated by Django 3.1.7 on 2021-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_remove_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='detailed_messages_stderr',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='detailed_messages',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('FE', 'Format Error'), ('SU', 'Submitting'), ('SE', 'Submission Error'), ('CO', 'Compiling'), ('CE', 'Compilation Error'), ('JU', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error')], default='SU', max_length=2),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
