# Generated by Django 3.1.7 on 2021-04-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20210406_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='messages',
            new_name='message',
        ),
    ]
